//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpdeskEspecialista.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProblemaSintoma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProblemaSintoma()
        {
            this.SintomaLog = new HashSet<SintomaLog>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ProblemaId { get; set; }
        public Nullable<int> SintomaId { get; set; }
    
        public virtual Problema Problema { get; set; }
        public virtual Sintoma Sintoma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SintomaLog> SintomaLog { get; set; }
    }
}
